# Generated by Django 4.2.20 on 2025-08-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='base_station',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='pole',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='statuses',
        ),
        migrations.AlterUniqueTogether(
            name='incidentstatushistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='incidentstatushistory',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incidentstatushistory',
            name='status',
        ),
    ]
