# Generated by Django 4.2.20 on 2025-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='is_email_from_yandex_tracker',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Было ли письмо отправлено из YandexTracker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='was_added_2_yandex_tracker',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Было ли письмо добавлено в YandexTracker'),
            preserve_default=False,
        ),
    ]
