# Generated by Django 4.2.20 on 2025-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emailmessage_is_email_from_yandex_tracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='email_subject',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True, verbose_name='Тема письма'),
        ),
    ]
