# Generated by Django 4.2.20 on 2025-08-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('emails', '0002_remove_incident_base_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='email_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='incidents.incident', verbose_name='Номер инцидента'),
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='IncidentStatus',
        ),
        migrations.DeleteModel(
            name='IncidentStatusHistory',
        ),
        migrations.DeleteModel(
            name='IncidentType',
        ),
    ]
