# Generated by Django 4.2.20 on 2025-08-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emailmessage_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='email_from',
            field=models.EmailField(db_index=True, max_length=32, verbose_name='Адрес отправителя'),
        ),
    ]
