# Generated by Django 4.2.20 on 2025-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_emailmessage_email_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='email_from',
            field=models.EmailField(db_index=True, max_length=64, verbose_name='Адрес отправителя'),
        ),
        migrations.AlterField(
            model_name='emailto',
            name='email_to',
            field=models.EmailField(max_length=64, verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='emailtocc',
            name='email_to',
            field=models.EmailField(max_length=64, verbose_name='Адрес получателя'),
        ),
    ]
