# Generated by Django 4.2.20 on 2025-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_emailmessage_email_from_alter_emailto_email_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='email_msg_id',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='ID сообщения'),
        ),
    ]
