# Generated by Django 4.2.20 on 2025-09-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_alter_emailmessage_email_msg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'папка писем',
                'verbose_name_plural': 'Папки писем',
            },
        ),
        migrations.AddConstraint(
            model_name='emailfolder',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_email_folder'),
        ),
    ]
