# Generated by Django 4.2.20 on 2025-09-08 12:59

from django.db import migrations, models
import django.db.models.deletion
import emails.models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_emailfolder_emailfolder_unique_email_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='folder',
            field=models.ForeignKey(default=emails.models.EmailFolder.get_inbox_id, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='email_messages', to='emails.emailfolder', verbose_name='Папка письма'),
        ),
    ]
