# Generated by Django 4.2.20 on 2025-11-18 11:36

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_emailmessage_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(blank=True, help_text='Необязательный файл с исходным письмом в формате MIME.', null=True, upload_to=core.utils.email_mime_upload_to, verbose_name='Файл с оригиналом письма (.eml)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('email_msg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_mime', to='emails.emailmessage', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'оригинальное письмо',
                'verbose_name_plural': 'Оригинальные письма',
            },
        ),
    ]
