# Generated by Django 4.2.20 on 2025-11-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_emailmime'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='need_2_add_in_yandex_tracker',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Необходимо ли перенести письмо в YandexTracker'),
        ),
    ]
