# Generated by Django 4.2.20 on 2025-11-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_emailmessage_need_2_add_in_yandex_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmime',
            name='created_at',
        ),
    ]
