# Generated by Django 4.2.20 on 2025-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_remove_emailmime_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emailmime',
            constraint=models.UniqueConstraint(fields=('email_msg', 'file_url'), name='unique_email_mime'),
        ),
    ]
