# Generated by Django 4.2.20 on 2026-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_emailmime_unique_email_mime'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='is_sent',
            field=models.BooleanField(default=True, verbose_name='Флаг было ли письмо отправленно через Cellery'),
        ),
    ]
