# Generated by Django 4.2.20 on 2026-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_emailmessage_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки'), ('retry', 'Повторная попытка')], db_index=True, default='sent', max_length=32, verbose_name='Статус отправки'),
        ),
    ]
