# Generated by Django 4.2.20 on 2026-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_remove_emailmessage_is_sent_emailmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailerr',
            name='email_msg_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='ID сообщения в почте'),
        ),
    ]
