# Generated by Django 4.2.20 on 2026-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_alter_emailerr_email_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreference',
            name='email_msg_references',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Ссылка на другие сообщения'),
        ),
    ]
