# Generated by Django 4.2.20 on 2026-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0016_alter_emailreference_email_msg_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата и время добавления в систему'),
        ),
    ]
