from datetime import timedelta

MAX_NOTIFICATION_TITLE_LEN = 64

MAX_NOTIFICATION_TEXT_LEN = 1024

MAX_NOTIFICATION_LEVEL_LEN = 16

NOTIFICATIONS_PER_PAGE = 50

OLD_NOTIFICATIONS_TTL = timedelta(days=7)

MAX_NOTIFICATION_PREWIE_LEN = 128
