# Generated by Django 4.2.20 on 2025-10-02 10:56

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_pendinguser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(help_text='Пароль должен содержать минимум 8 символов, не может быть полностью числовым, не должен быть похож на имя пользователя и не должен быть слишком простым.', max_length=128, validators=[users.validators.validate_pending_password]),
        ),
    ]
