# Generated by Django 4.2.20 on 2025-10-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_workschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='friday',
            field=models.BooleanField(default=True, verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='monday',
            field=models.BooleanField(default=True, verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='thursday',
            field=models.BooleanField(default=True, verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='tuesday',
            field=models.BooleanField(default=True, verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='wednesday',
            field=models.BooleanField(default=True, verbose_name='Среда'),
        ),
    ]
