# Generated by Django 4.2.20 on 2025-12-16 07:52

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.validate_pending_email], verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(help_text='Пароль должен содержать минимум 8 символов.\nНе может состоять только из цифр.\nНе должен быть похож на имя пользователя.\nНе должен быть слишком простым.', max_length=128, validators=[users.validators.validate_pending_password]),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(help_text='Имя пользователя должно содержать минимум 4 символов.\nРазрешены: латинские буквы, цифры, точка, нижнее подчёркивание или тире.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в имени пользователя. Разрешены только: английские буквы, цифры и . - _', regex='^[a-zA-Z0-9._-]+$'), django.core.validators.MinLengthValidator(limit_value=4, message='Имя пользователя должно содержать минимум 4 символа.'), users.validators.validate_pending_username], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите аватар пользователя в формате JPG или PNG.', null=True, upload_to='public/users', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД.', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.validate_user_email], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('dispatch', 'Диспетчер')], default='guest', help_text='Выберите роль пользователя.', max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Имя пользователя должно содержать минимум 4 символов.\nРазрешены: латинские буквы, цифры, точка, нижнее подчёркивание или тире.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в имени пользователя. Разрешены только: английские буквы, цифры и . - _', regex='^[a-zA-Z0-9._-]+$'), django.core.validators.MinLengthValidator(limit_value=4, message='Имя пользователя должно содержать минимум 4 символа.'), users.validators.validate_user_username], verbose_name='Имя пользователя'),
        ),
    ]
