# Generated by Django 4.2.20 on 2025-12-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_alter_pendinguser_email_alter_pendinguser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('dispatch', 'Диспетчер'), ('energy', 'Энергетик')], default='guest', help_text='Выберите роль пользователя.', max_length=16, verbose_name='Роль'),
        ),
    ]
