# Generated by Django 4.2.20 on 2026-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, help_text='Выберите стандартную иконку вместо загрузки фото.', max_length=32, null=True, verbose_name='Иконка профиля'),
        ),
    ]
