# Generated by Django 4.2.20 on 2026-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_user_default_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('1__robot.png', 'Робот диспетчер')], help_text='Выберите стандартную иконку вместо загрузки фото.', max_length=32, null=True, verbose_name='Иконка профиля'),
        ),
    ]
