# Generated by Django 4.2.20 on 2026-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_alter_user_default_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('dispatch', 'Диспетчер'), ('energy', 'Энергетик')], db_index=True, default='guest', help_text='Выберите роль пользователя.', max_length=16, verbose_name='Роль'),
        ),
    ]
