# Generated by Django 4.2.20 on 2026-04-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('1__robot.png', 'Робот-помощник'), ('2__astronaut.png', 'Исследователь космоса'), ('3__pilot.png', 'Верный штурман'), ('4__fox.png', 'Мудрый лис'), ('5__koala.png', 'Спокойная коала'), ('6__snowy.png', 'Ночной дозор'), ('7__knight.png', 'Страж порядка'), ('8__ninja.png', 'Профи-ниндзя'), ('9__wizard.png', 'Маг решений')], help_text='Выберите стандартную иконку вместо загрузки фото.', max_length=32, null=True, verbose_name='Иконка профиля'),
        ),
    ]
