# Generated by Django 4.2.20 on 2026-05-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_alter_user_default_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД.', null=True, verbose_name='День рождения'),
        ),
    ]
