# Generated by Django 4.2.20 on 2026-05-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0012_region_responsible_manager'),
        ('users', '0076_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avr_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ts.avrcontractor', verbose_name='Подрядчик по АВР'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('dispatch', 'Диспетчер'), ('energy', 'Энергетик'), ('avr_contractor', 'Подрядчик по АВР')], db_index=True, default='guest', help_text='Выберите роль пользователя.', max_length=16, verbose_name='Роль'),
        ),
    ]
