# Generated by Django 4.2.20 on 2026-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_user_avr_contractor_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('dispatch', 'Диспетчер'), ('energy', 'Энергетик'), ('avr_contractor', 'Подрядчик')], db_index=True, default='guest', help_text='Выберите роль пользователя.', max_length=16, verbose_name='Роль'),
        ),
    ]
