# Generated by Django 4.2.20 on 2026-07-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата и время последнего посещения сайта.', null=True, verbose_name='Последний онлайн'),
        ),
    ]
