# Generated by Django 4.2.20 on 2026-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_user_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('intern', 'Стажер'), ('dispatch', 'Диспетчер'), ('avr_contractor', 'Подрядчик'), ('energy', 'Энергетик')], db_index=True, default='guest', help_text='Выберите роль пользователя.', max_length=16, verbose_name='Роль'),
        ),
    ]
