# Generated by Django 4.2.20 on 2026-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0012_region_responsible_manager'),
        ('users', '0080_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='incident_regions',
            field=models.ManyToManyField(blank=True, help_text='Регионы, за которые отвечает пользователь по инцидентам.', related_name='users', to='ts.region', verbose_name='Регионы инцидентов'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_incident_responsible',
            field=models.BooleanField(db_index=True, default=False, help_text='Пользователь является ответственным по инцидентам.', verbose_name='Ответственный по инцидентам'),
        ),
    ]
