# Generated by Django 4.2.20 on 2026-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_user_incident_regions_user_is_incident_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД.', null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
