# Generated by Django 4.2.20 on 2026-09-18 10:58

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_pendinguser_date_of_birth_pendinguser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Российский номер, например: +7 800 234-67-66.', max_length=11, null=True, validators=[users.validators.validate_ru_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(help_text='Пароль должен содержать минимум 8 символов.\nНе может состоять только из цифр.\nНе должен быть похож на логин.\nНе должен быть слишком простым.', max_length=128, validators=[users.validators.validate_pending_password]),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(help_text='Логин должен содержать минимум 4 символов.\nРазрешены: латинские буквы, цифры, точка, нижнее подчёркивание или тире.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в логине пользователя. Разрешены только: английские буквы, цифры и . - _', regex='^[a-zA-Z0-9._-]+$'), django.core.validators.MinLengthValidator(limit_value=4, message='Логин должен содержать минимум 4 символа.'), users.validators.validate_pending_username], verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Логин должен содержать минимум 4 символов.\nРазрешены: латинские буквы, цифры, точка, нижнее подчёркивание или тире.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в логине пользователя. Разрешены только: английские буквы, цифры и . - _', regex='^[a-zA-Z0-9._-]+$'), django.core.validators.MinLengthValidator(limit_value=4, message='Логин должен содержать минимум 4 символа.'), users.validators.validate_user_username], verbose_name='Логин'),
        ),
    ]
