import os

MODEM_STATUSES_PER_PAGE = 30
POLE_STATUSES_PER_PAGE = 30
MODEM_LEVELS_PER_PAGE = 30

MODEMS_PER_PAGE = 30

POLE_UP_ACTION_KEY = 'siteTurnedOn'
MONITORING_2_BASE_URL = os.getenv('MONITORING_2_BASE_URL').rstrip('/')
NOTIFICATION_POLE_UP_URL = (
    f'{MONITORING_2_BASE_URL}'
    f'/api/integration/notifications/modem/'
    f'{POLE_UP_ACTION_KEY}/sent'
)
NOTIFICATION_FAILED_CACHE_KEY = 'notify_pole_up:failed_ips'
NOTIFICATION_FAILED_CACHE_TIMEOUT = 7 * 24 * 60 * 60  # 7 дней

RHU_NEW_ID = 102
HU_NEVA_NEW_ID = 107

NORMAL_STATUS_ID = 1000

UNDEFINED_POLE_CASE = 'undefined'
CHUNKED_MONITORING_2_QS = 1000
MONITORING_2_EQUIPMENT_CACHE_TTL = 900
MONITORING_2_EQUIPMENT_CACHE_KEY_PREFIX = 'monitoring_2_equipment'
MAX_EQUIPMENT_PER_POLE = 21

MODEM_NORMAL_STATUS_ID = 1000
