# Generated by Django 4.2.20 on 2025-12-03 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала выполнения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения выполнения')),
                ('task_name', models.CharField(db_index=True, max_length=256, verbose_name='Название задачи')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True, verbose_name='ID задачи в Celery')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('started', 'В процессе'), ('success', 'Завершена'), ("('failed', 'Ошибка')", 'Failed'), ("('retry', 'Повтор')", 'Retry')], db_index=True, default='queued', max_length=32, verbose_name='Статус задачи')),
                ('attempts', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущая попытка')),
                ('max_attempts', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальное кол-во попыток')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Последняя ошибка')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Данные задачи')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_outgoi_status_144597_idx'), models.Index(fields=['task_name'], name='core_outgoi_task_na_4d2140_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='outgoingtask',
            constraint=models.CheckConstraint(check=models.Q(('attempts__lte', models.F('max_attempts'))), name='outgoingtask_attempts_lte_max'),
        ),
    ]
