# Generated by Django 4.2.20 on 2025-12-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_celerytask_delete_outgoingtask_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryTask',
        ),
    ]
