# Generated by Django 4.2.20 on 2026-06-15 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0016_alter_emailreference_email_msg_references'),
        ('ts', '0012_region_responsible_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('power_off', 'Отключение питания'), ('preventive_maintenance', 'Плановое обслуживание'), ('equipment_upgrade', 'Модернизация оборудования'), ('cable_replacement', 'Замена кабельной линии'), ('installation', 'Установка нового оборудования'), ('inspection', 'Инспекция / Обследование'), ('other', 'Иное')], db_index=True, max_length=32, verbose_name='Причина')),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время начала ПЛР')),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время окончания ПЛР')),
                ('insert_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время добавления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_works', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'ПЛР',
                'verbose_name_plural': 'Плановые работы',
            },
        ),
        migrations.CreateModel(
            name='PlannedWorkEmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления в связь')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailmessage')),
                ('planned_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_links', to='planned_work.plannedwork')),
            ],
            options={
                'ordering': ['-added_at', '-id'],
                'unique_together': {('planned_work', 'email')},
            },
        ),
        migrations.AddField(
            model_name='plannedwork',
            name='emails',
            field=models.ManyToManyField(blank=True, help_text='Письма, связанные с данной плановой работой', related_name='planned_works', through='planned_work.PlannedWorkEmailLink', to='emails.emailmessage', verbose_name='Связанные письма'),
        ),
        migrations.AddField(
            model_name='plannedwork',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_works', to='ts.pole', verbose_name='Опора'),
        ),
        migrations.CreateModel(
            name='PlannedWorkChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Название поля модели', max_length=256, verbose_name='Поле')),
                ('old_value', models.CharField(blank=True, help_text='JSON строка или текст старого значения', max_length=1024, null=True, verbose_name='Старое значение')),
                ('new_value', models.CharField(blank=True, help_text='JSON строка или текст нового значения', max_length=1024, null=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил пользователь')),
                ('planned_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='planned_work.plannedwork', verbose_name='Плановая работа')),
            ],
            options={
                'verbose_name': 'журнал',
                'verbose_name_plural': 'Журналы изменений',
                'ordering': ['-created_at', 'field_name', 'id'],
                'indexes': [models.Index(fields=['planned_work', '-created_at'], name='planned_wor_planned_d61002_idx')],
                'unique_together': {('planned_work', 'field_name', 'created_at')},
            },
        ),
        migrations.AddConstraint(
            model_name='plannedwork',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='planned_work_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='plannedwork',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('pole', 'reason'), name='unique_open_planned_work_per_pole_reason'),
        ),
        migrations.AddConstraint(
            model_name='plannedwork',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', False)), fields=('pole', 'reason', 'end_date'), name='unique_planned_work_end_date'),
        ),
        migrations.AddConstraint(
            model_name='plannedwork',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', False)), fields=('pole', 'reason', 'start_date'), name='unique_planned_work_start_date'),
        ),
    ]
