# Generated by Django 4.2.20 on 2026-06-08 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0016_alter_emailreference_email_msg_references'),
        ('ts', '0012_region_responsible_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('power_off', 'Отключение питания'), ('preventive_maintenance', 'Плановое обслуживание'), ('equipment_upgrade', 'Модернизация оборудования'), ('cable_replacement', 'Замена кабельной линии'), ('installation', 'Установка нового оборудования'), ('inspection', 'Инспекция / Обследование'), ('other', 'Иное')], db_index=True, max_length=32, verbose_name='Причина')),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время начала ПЛР')),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время окончания ПЛР')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_works', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('emails', models.ManyToManyField(blank=True, help_text='Письма, связанные с данной плановой работой', related_name='planned_works', to='emails.emailmessage', verbose_name='Связанные письма')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_works', to='ts.pole', verbose_name='Опора')),
            ],
            options={
                'verbose_name': 'ПЛР',
                'verbose_name_plural': 'Плановые работы',
            },
        ),
        migrations.AddConstraint(
            model_name='plannedwork',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='planned_work_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='plannedwork',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('pole', 'reason'), name='unique_open_planned_work_per_pole_reason'),
        ),
        migrations.AddConstraint(
            model_name='plannedwork',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', False)), fields=('pole', 'reason', 'end_date'), name='unique_planned_work_end_date'),
        ),
        migrations.AddConstraint(
            model_name='plannedwork',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', False)), fields=('pole', 'reason', 'start_date'), name='unique_planned_work_start_date'),
        ),
    ]
