# Generated by Django 4.2.20 on 2026-06-10 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planned_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedwork',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время добавления'),
            preserve_default=False,
        ),
    ]
