# Generated by Django 4.2.20 on 2026-06-15 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planned_work', '0002_plannedwork_insert_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedWorkChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Название поля модели', max_length=256, verbose_name='Поле')),
                ('old_value', models.CharField(blank=True, help_text='JSON строка или текст старого значения', max_length=1024, null=True, verbose_name='Старое значение')),
                ('new_value', models.CharField(blank=True, help_text='JSON строка или текст нового значения', max_length=1024, null=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил пользователь')),
                ('planned_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='planned_work.plannedwork', verbose_name='Плановая работа')),
            ],
            options={
                'verbose_name': 'журнал',
                'verbose_name_plural': 'Журналы изменений',
                'ordering': ['-created_at', 'field_name', 'id'],
                'indexes': [models.Index(fields=['planned_work', '-created_at'], name='planned_wor_planned_d61002_idx')],
                'unique_together': {('planned_work', 'field_name', 'created_at')},
            },
        ),
    ]
