# Generated by Django 4.2.20 on 2025-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrcontractor',
            name='project_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='Идентификатор проекта АВР'),
            preserve_default=False,
        ),
    ]
