# Generated by Django 4.2.20 on 2025-08-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0002_avrcontractor_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avrcontractor',
            name='project_id',
        ),
    ]
