# Generated by Django 4.2.20 on 2025-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0003_remove_avrcontractor_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorphone',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Телефон'),
        ),
    ]
