# Generated by Django 4.2.20 on 2025-08-20 15:41

from django.db import migrations, models
import django.db.models.deletion
import ts.models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0004_alter_contractorphone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestationoperator',
            name='operator_group',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Группа операторов'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='avr_contractor',
            field=models.ForeignKey(default=ts.models.get_default_contractor, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='poles', to='ts.avrcontractor', verbose_name='Подрядчик по АВР'),
        ),
    ]
