# Generated by Django 4.2.20 on 2025-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0005_alter_basestationoperator_operator_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoremail',
            name='email',
            field=models.EmailField(db_index=True, max_length=64, unique=True, verbose_name='email'),
        ),
    ]
