# Generated by Django 4.2.20 on 2025-09-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0006_alter_contractoremail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='region_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Регион (ru)'),
        ),
    ]
