# Generated by Django 4.2.20 on 2025-10-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0007_pole_region_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avrcontractor',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='avrcontractor',
            name='phones',
        ),
        migrations.CreateModel(
            name='PoleContractorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_phones', to='ts.avrcontractor')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts.contractorphone')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pole_phones', to='ts.pole')),
            ],
            options={
                'verbose_name': 'Телефон подрядчика для опоры',
                'verbose_name_plural': 'Телефоны подрядчиков для опор',
                'unique_together': {('pole', 'contractor', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='PoleContractorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_emails', to='ts.avrcontractor')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts.contractoremail')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pole_emails', to='ts.pole')),
            ],
            options={
                'verbose_name': 'Email подрядчика для опоры',
                'verbose_name_plural': 'Emails подрядчиков для опор',
                'unique_together': {('pole', 'contractor', 'email')},
            },
        ),
        migrations.AddField(
            model_name='pole',
            name='avr_emails',
            field=models.ManyToManyField(related_name='poles', through='ts.PoleContractorEmail', to='ts.contractoremail', verbose_name='Emails подрядчиков на опоре'),
        ),
        migrations.AddField(
            model_name='pole',
            name='avr_phones',
            field=models.ManyToManyField(related_name='poles', through='ts.PoleContractorPhone', to='ts.contractorphone', verbose_name='Телефоны подрядчиков на опоре'),
        ),
    ]
