# Generated by Django 4.2.20 on 2025-10-22 08:19

from django.db import migrations, models
import django.db.models.deletion
import ts.models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0008_remove_avrcontractor_emails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polecontractoremail',
            options={'verbose_name': 'АВР email подрядчика для опоры', 'verbose_name_plural': 'АВР emails подрядчиков для опор'},
        ),
        migrations.AlterModelOptions(
            name='polecontractorphone',
            options={'verbose_name': 'АВР телефон подрядчика для опоры', 'verbose_name_plural': 'АВР телефоны подрядчиков для опор'},
        ),
        migrations.RemoveField(
            model_name='pole',
            name='region_ru',
        ),
        migrations.AlterField(
            model_name='pole',
            name='avr_emails',
            field=models.ManyToManyField(related_name='poles', through='ts.PoleContractorEmail', to='ts.contractoremail', verbose_name='Emails подрядчиков АВР на опоре'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='avr_phones',
            field=models.ManyToManyField(related_name='poles', through='ts.PoleContractorPhone', to='ts.contractorphone', verbose_name='Телефоны подрядчиков АВР на опоре'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_en', models.CharField(max_length=256, unique=True, verbose_name='Регион')),
                ('region_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Регион (ru)')),
                ('rvr_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='ts.contractoremail', verbose_name='Email подрядчика по РВР')),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AlterField(
            model_name='pole',
            name='region',
            field=models.ForeignKey(default=ts.models.get_default_region, on_delete=django.db.models.deletion.PROTECT, related_name='poles', to='ts.region', verbose_name='Регион'),
        ),
    ]
