# Generated by Django 4.2.20 on 2025-12-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0009_alter_polecontractoremail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Макрорегион НБ')),
            ],
            options={
                'verbose_name': 'макрорегион',
                'verbose_name_plural': 'Макрорегионы',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='macro_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='ts.macroregion', verbose_name='Макрорегион'),
        ),
    ]
