# Generated by Django 4.2.20 on 2025-12-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0010_macroregion_region_macro_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='macro_region',
            new_name='macroregion',
        ),
    ]
