# Generated by Django 4.2.20 on 2026-05-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0011_rename_macro_region_region_macroregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='responsible_manager',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Ответстенный'),
        ),
    ]
