# Generated by Django 4.2.20 on 2026-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0012_region_responsible_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestation',
            name='sla_contract_deadline',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок устранения аварии по договору (мин)'),
        ),
    ]
