# Generated by Django 4.2.20 on 2026-09-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0013_basestation_sla_contract_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basestation',
            name='sla_contract_deadline',
        ),
        migrations.CreateModel(
            name='BaseStationOperatorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_contract_deadline', models.IntegerField(blank=True, null=True, verbose_name='Срок устранения аварии по договору (мин)')),
                ('base_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ts.basestation', verbose_name='Базовая станция')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ts.basestationoperator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'договор оператора на БС',
                'verbose_name_plural': 'Договора операторов на БС',
            },
        ),
        migrations.AddConstraint(
            model_name='basestationoperatorcontract',
            constraint=models.UniqueConstraint(fields=('base_station', 'operator'), name='unique_bs_operator_contract'),
        ),
    ]
