# Generated by Django 4.2.20 on 2026-09-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0014_remove_basestation_sla_contract_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestationoperatorcontract',
            name='base_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_contracts', to='ts.basestation', verbose_name='Базовая станция'),
        ),
        migrations.AlterField(
            model_name='basestationoperatorcontract',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs_contracts', to='ts.basestationoperator', verbose_name='Оператор'),
        ),
    ]
