# Generated by Django 4.2.20 on 2026-10-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0015_alter_basestationoperatorcontract_base_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='rvr_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='ts.contractoremail', verbose_name='Базовый Email подрядчика по РВР (по умолчанию)'),
        ),
    ]
