# Generated by Django 4.2.20 on 2026-10-09 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0016_alter_region_rvr_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolsContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Имя подрядчика')),
                ('is_avr_contractor', models.BooleanField(default=False, verbose_name='Выполняет работы по АВР')),
                ('email', models.ManyToManyField(blank=True, related_name='vols_contractors', to='ts.contractoremail', verbose_name='Email адреса')),
            ],
            options={
                'verbose_name': 'подрядчик ВОЛС',
                'verbose_name_plural': 'Подрядчики ВОЛС',
            },
        ),
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField(unique=True, verbose_name='ID ВОЛС в TS')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название ВОЛС')),
                ('base_stations', models.ManyToManyField(blank=True, related_name='vols', to='ts.basestation', verbose_name='Базовые станции')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vols', to='ts.volscontractor', verbose_name='Подрядчик ВОЛС')),
            ],
            options={
                'verbose_name': 'ВОЛС',
                'verbose_name_plural': 'ВОЛСы',
            },
        ),
    ]
