# Generated by Django 4.2.20 on 2026-08-12 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modem_ip', models.GenericIPAddressField(verbose_name='IP адрес сим карты')),
                ('modem_mac', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Введите корректный MAC-адрес (например, AA:BB:CC:DD:EE:FF или AA-BB-CC-DD-EE-FF)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='MAC-адрес')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'АО',
                'verbose_name_plural': 'Активное оборудование',
            },
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('modem_ip', 'modem_mac'), name='unique_modem_ip_mac'),
        ),
    ]
