import os
from datetime import timedelta

MQTT_MONGO_DB_URL = os.environ.get('MQTT_MONGO_DB_URL')
MQTT_MONGO_DB_NAME = 'mqtt'
MQTT_MONGO_DB_COLLECTION = 'data'

MQTT_CONN_TIMEOUT = 5000  # мс
MQTT_BATCH_SIZE = 10_000
MONGO_RETENTION_TTL = timedelta(days=1)

MQTT_DB_BATCH_SIZE = 1000

MAX_MAC_LEN = 17
MAX_DEVICE_VERSION_LEN = 64
MAX_NETWORK_TYPE_LEN = 8
MAX_OPERATOR_CODE_LEN = 16
MAX_OPERATOR_NAME_LEN = 64

DEVICE_PER_PAGE = 50
CELL_INFO_PER_PAGE = 50
DEVICE_OPERATOR_PER_PAGE = 50
OPERATOR_PER_PAGE = 50

CELL_INFO_TTL = timedelta(days=14)
