import os
from datetime import timedelta

MQTT_MONGO_DB_URL = os.environ.get('MQTT_MONGO_DB_URL')
MQTT_MONGO_DB_NAME = 'mqtt'
MQTT_MONGO_DB_COLLECTION = 'data'

MQTT_CONN_TIMEOUT = 5000  # мс
MQTT_BATCH_SIZE = 10_000
MONGO_RETENTION_TTL = timedelta(days=1)

MQTT_DB_BATCH_SIZE = 1000
MQTT_DEVICE_BATCH_SIZE = 100  # Очень тяжелые запросы

MAX_MAC_LEN = 17
MAX_DEVICE_VERSION_LEN = 64
MAX_NETWORK_TYPE_LEN = 8
MAX_OPERATOR_CODE_LEN = 16
MAX_OPERATOR_NAME_LEN = 64

DEVICE_PER_PAGE = 50
CELL_PER_PAGE = 50
CELL_MEASSURE_PER_PAGE = 50
OPERATOR_PER_PAGE = 50

CELL_MEASSURE_TTL = timedelta(days=3)
ERR_PARSER_MSG_LIMIT = 300  # символов

MAX_MONGO_ID_LEN = 24


class CellMeasurConstraints:
    MIN_RSRP_VAL = -140
    MAX_RSRP_VAL = -44

    MIN_RSRQ_VAL = -43
    MAX_RSRQ_VAL = 0

    MIN_ECNO_VAL = -24
    MAX_ECNO_VAL = 10

    MIN_RSCP_VAL = -125
    MAX_RSCP_VAL = 0

    MIN_C1_VAL = -100
    MAX_C1_VAL = 200

    MIN_RXLEV_VAL = 0
    MAX_RXLEV_VAL = 63

    MIN_RSSI_VAL = -120
    MAX_RSSI_VAL = 0

    MIN_INDEX_VAL = 0
    MAX_INDEX_VAL = 100
