import os
import re

MSYS_MODEMS_PER_PAGE = 100
MSYS_STATUSES_PER_PAGE = 100
MSYS_POLES_PER_PAGE = 100

NORMAL_POLES_CACHE_TIMEOUT = 900  # 15 мин

UNDEFINED_POLE_CASE = 'undefined'

MONITORING_EQUIPMENT_CACHE_TTL = 900  # БД мониторинга медленная
MONITORING_EQUIPMENT_CACHE_KEY = 'monitoring_equipment'
CHUNKED_MONITORING_QS = 1000

MAX_MODEM_IP_LEN = 40

MAX_NEW_RHU_NOTIFICATION = 1000

TOP_N_NEAREST_POLES = 3

GPS_NUMBER_DECIMAL_PLACES = 5

COORDINATE_PATTERN = re.compile(r'^-?\d+(\.\d+)?$')

FACTORY_EXCLUSION_RADIUS = 750  # метров
MAX_MIN_LEN_BETWEEN_MODEM_AND_POLE = 500  # метров
TRETHHOLD_RATIO_BETWEEN_MODEM_AND_POLE = 1.5  # 50% от дистанции до главной

MONITORING_CHUNK_SIZE = 1000

NOTIFY_NEW_POLE_EMAILS = [
    email.strip()
    for email in os.getenv('NOTIFY_NEW_POLE_EMAILS').split(',')
    if email.strip()
]

NOTIFY_NEW_POLE_LOCK_KEY = 'lock_notify_pole_up'
NOTIFY_NEW_POLE_LOCK_TIMEOUT = 3600
