MSYS_MODEMS_PER_PAGE = 100
MSYS_STATUSES_PER_PAGE = 100
MSYS_POLES_PER_PAGE = 100

NORMAL_POLES_CACHE_TIMEOUT = 900  # 15 мин

UNDEFINED_POLE_CASE = 'undefined'

MONITORING_EQUIPMENT_CACHE_TTL = 600
MONITORING_EQUIPMENT_CACHE_KEY = 'monitoring_equipment'
CHUNKED_MONITORING_QS = 1000

MAX_MODEM_IP_LEN = 40
