# Generated by Django 4.2.20 on 2026-04-07 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Индекс в списке')),
                ('operator_code', models.CharField(db_index=True, max_length=16, verbose_name='Код оператора (MNC+MCC)')),
                ('operator_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя оператора')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Forbidden (Запрещена)'), (1, 'Current (Выбрана)'), (2, 'Available (Доступна)'), (3, 'Home (Домашняя)')], null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'оператор соты',
                'verbose_name_plural': 'Операторы сот',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CellInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Индекс соты в списке')),
                ('cell_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Cell ID')),
                ('mcc_mnc', models.CharField(blank=True, max_length=16, null=True, verbose_name='MCC-MNC код оператора')),
                ('network_type', models.CharField(blank=True, choices=[('2G', 'GSM (2G)'), ('3G', 'UMTS (3G)'), ('4G', 'LTE (4G)'), ('5G', 'NR (5G)')], max_length=8, null=True, verbose_name='Тип сети')),
                ('freq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Частота')),
                ('tac', models.PositiveIntegerField(blank=True, help_text='TAC (Tracking Area Code) - идентификаторы групп базовых станций в сотовой связи 4G', null=True, verbose_name='TAC (4G)')),
                ('lac', models.PositiveIntegerField(blank=True, help_text='LAC (Location Area Code) - идентификаторы групп базовых станций в сотовой связи 2G и 3G', null=True, verbose_name='LAC (2G/3G)')),
                ('rsrp', models.SmallIntegerField(blank=True, help_text=('RSRP (Reference Signal Received Power) - уровень сигнала 4G',), null=True, verbose_name='RSRP (dBm)')),
                ('rsrq', models.SmallIntegerField(blank=True, help_text=('RSRQ (Reference Signal Received Quality) - качество сигнала 4G',), null=True, verbose_name='RSRQ (dB)')),
                ('pci', models.PositiveSmallIntegerField(blank=True, help_text='PCI (Physical Cell ID) — идентификатор базовой станции в сетях 4G', null=True, verbose_name='PCI')),
                ('earfcn', models.PositiveIntegerField(blank=True, help_text='EARFCN (E-UTRA Absolute Radio Frequency Channel Number) - уникальный номер частоты для 4G', null=True, verbose_name='EARFCN')),
                ('rscp', models.SmallIntegerField(blank=True, help_text='RSCP (Received signal Code power) - уровень сигнала 3G', null=True, verbose_name='RSCP (dBm)')),
                ('ecno', models.SmallIntegerField(blank=True, help_text='Ec/No (Ratio of energy per modulating bit to the noise spectral density) - качество сигнала 3G', null=True, verbose_name='Ec/No (dB)')),
                ('psc', models.PositiveSmallIntegerField(blank=True, help_text='PSC (Primary Scrambling Code) - идентификатор базовой станции в сетях 3G', null=True, verbose_name='PSC')),
                ('rssi', models.SmallIntegerField(blank=True, help_text='RSSI (Received Signal Strength Indicator) - уровень сигнала 2G', null=True, verbose_name='RSSI (dBm)')),
                ('rxlev', models.SmallIntegerField(blank=True, help_text='RXLEV (Received Signal Level) - показатель мощности радиосигнала в сетях 2G', null=True, verbose_name='RXLEV')),
                ('bsic', models.PositiveSmallIntegerField(blank=True, help_text='BSIC (Base station ID code) - идентификатор базовой станции в сетях 2G', null=True, verbose_name='BSIC')),
                ('c1', models.PositiveSmallIntegerField(blank=True, help_text='C1 (Cell selection criterion) - критерий «пригодности» сигнала для работы в сетях 2G', null=True, verbose_name='C1')),
            ],
            options={
                'verbose_name': 'данные соты',
                'verbose_name_plural': 'Данные сот',
                'ordering': ['mqtt', '-rsrp', '-rscp', '-rssi', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17, verbose_name='MAC адрес контроллера')),
                ('event_datetime', models.DateTimeField(db_index=True, verbose_name='Дата и время регистрации')),
                ('gps_lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('gps_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('sys_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='Версия контроллера')),
                ('app_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='Версия прошивки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'Устройства',
                'indexes': [models.Index(fields=['mac_address', '-event_datetime'], name='mqtt_mqtt_mac_add_5e0c0b_idx'), models.Index(fields=['gps_lat', 'gps_lon'], name='mqtt_mqtt_gps_lat_3921e4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mqtt',
            constraint=models.UniqueConstraint(fields=('mac_address', 'event_datetime'), name='unique_mac_event'),
        ),
        migrations.AddField(
            model_name='cellinfo',
            name='mqtt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='mqtt.mqtt', verbose_name='устройство'),
        ),
        migrations.AddField(
            model_name='availableoperator',
            name='mqtt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='mqtt.mqtt', verbose_name='Устройства'),
        ),
        migrations.AddIndex(
            model_name='cellinfo',
            index=models.Index(fields=['mqtt', 'cell_id'], name='mqtt_cellin_mqtt_id_c42b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cellinfo',
            index=models.Index(fields=['network_type', 'rsrp'], name='mqtt_cellin_network_e10b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='cellinfo',
            index=models.Index(fields=['network_type', 'rscp'], name='mqtt_cellin_network_9a0509_idx'),
        ),
        migrations.AddIndex(
            model_name='cellinfo',
            index=models.Index(fields=['network_type', 'rssi'], name='mqtt_cellin_network_04880e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cellinfo',
            constraint=models.UniqueConstraint(fields=('mqtt', 'cell_id'), name='unique_mqtt_cell'),
        ),
        migrations.AlterUniqueTogether(
            name='availableoperator',
            unique_together={('mqtt', 'operator_code')},
        ),
    ]
