# Generated by Django 4.2.20 on 2026-04-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableOperator',
            new_name='CellOperator',
        ),
    ]
