# Generated by Django 4.2.20 on 2026-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_rename_availableoperator_celloperator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MQTT',
            new_name='Device',
        ),
        migrations.AlterModelOptions(
            name='cellinfo',
            options={'ordering': ['device', '-rsrp', '-rscp', '-rssi', 'id'], 'verbose_name': 'данные соты', 'verbose_name_plural': 'Данные сот'},
        ),
        migrations.RemoveConstraint(
            model_name='cellinfo',
            name='unique_mqtt_cell',
        ),
        migrations.RemoveIndex(
            model_name='cellinfo',
            name='mqtt_cellin_mqtt_id_c42b5d_idx',
        ),
        migrations.RenameField(
            model_name='cellinfo',
            old_name='mqtt',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='celloperator',
            old_name='mqtt',
            new_name='device',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='mqtt_device_mac_add_63b2af_idx',
            old_name='mqtt_mqtt_mac_add_5e0c0b_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='mqtt_device_gps_lat_05737b_idx',
            old_name='mqtt_mqtt_gps_lat_3921e4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='celloperator',
            unique_together={('device', 'operator_code')},
        ),
        migrations.AddIndex(
            model_name='cellinfo',
            index=models.Index(fields=['device', 'cell_id'], name='mqtt_cellin_device__0c50af_idx'),
        ),
        migrations.AddConstraint(
            model_name='cellinfo',
            constraint=models.UniqueConstraint(fields=('device', 'cell_id'), name='unique_device_cell'),
        ),
    ]
