# Generated by Django 4.2.20 on 2026-04-07 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_rename_mqtt_device_alter_cellinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellinfo',
            options={'ordering': ['-event_datetime', 'device', '-rsrp', '-rscp', '-rssi', 'id'], 'verbose_name': 'данные соты', 'verbose_name_plural': 'Данные сот'},
        ),
        migrations.AlterModelOptions(
            name='celloperator',
            options={'ordering': ['-event_datetime', 'device', 'index', 'id'], 'verbose_name': 'оператор соты', 'verbose_name_plural': 'Операторы сот'},
        ),
        migrations.RemoveConstraint(
            model_name='cellinfo',
            name='unique_device_cell',
        ),
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_mac_event',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='mqtt_device_mac_add_63b2af_idx',
        ),
        migrations.AlterUniqueTogether(
            name='celloperator',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='device',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='cellinfo',
            name='event_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время регистрации'),
        ),
        migrations.AddField(
            model_name='celloperator',
            name='event_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время регистрации'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время последнего события'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True, verbose_name='MAC адрес контроллера'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mac_address', '-last_seen'], name='mqtt_device_mac_add_2f1b24_idx'),
        ),
        migrations.AddConstraint(
            model_name='cellinfo',
            constraint=models.UniqueConstraint(fields=('device', 'cell_id', 'event_datetime'), name='unique_device_cell'),
        ),
        migrations.AddConstraint(
            model_name='celloperator',
            constraint=models.UniqueConstraint(fields=('device', 'operator_code', 'event_datetime'), name='unique_device_operator_code'),
        ),
    ]
