# Generated by Django 4.2.20 on 2026-04-07 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_alter_cellinfo_options_alter_celloperator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Индекс в списке')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Forbidden (Запрещена)'), (1, 'Current (Выбрана)'), (2, 'Available (Доступна)'), (3, 'Home (Домашняя)')], null=True, verbose_name='Статус')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Видел последний раз')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='mqtt.device', verbose_name='Устройства')),
            ],
            options={
                'verbose_name': 'видимый оператор',
                'verbose_name_plural': 'Видимые операторы',
                'ordering': ('-last_seen', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Код оператора (MNC+MCC)')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя оператора')),
            ],
            options={
                'verbose_name': 'оператор связи',
                'verbose_name_plural': 'Операторы связи',
                'ordering': ('code', 'id'),
            },
        ),
        migrations.DeleteModel(
            name='CellOperator',
        ),
        migrations.AddField(
            model_name='deviceoperator',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by_devices', to='mqtt.operator', verbose_name='Оператор'),
        ),
        migrations.AddConstraint(
            model_name='deviceoperator',
            constraint=models.UniqueConstraint(fields=('device', 'operator'), name='unique_device_operator_pair'),
        ),
    ]
