# Generated by Django 4.2.20 on 2026-04-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0005_deviceoperator_operator_delete_celloperator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinfo',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='mqtt.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='deviceoperator',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='mqtt.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='code',
            field=models.CharField(max_length=16, unique=True, verbose_name='Код оператора (MNC+MCC)'),
        ),
    ]
