# Generated by Django 4.2.20 on 2026-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_alter_cellinfo_device_alter_deviceoperator_device_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ('name', 'id'), 'verbose_name': 'оператор связи', 'verbose_name_plural': 'Операторы связи'},
        ),
        migrations.AlterField(
            model_name='cellinfo',
            name='c1',
            field=models.SmallIntegerField(blank=True, help_text='C1 (Cell selection criterion) - критерий «пригодности» сигнала для работы в сетях 2G', null=True, verbose_name='C1'),
        ),
    ]
