# Generated by Django 4.2.20 on 2026-04-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0007_alter_operator_options_alter_cellinfo_c1'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cellinfo',
            name='mqtt_cellin_network_e10b5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='cellinfo',
            name='mqtt_cellin_network_9a0509_idx',
        ),
        migrations.RemoveIndex(
            model_name='cellinfo',
            name='mqtt_cellin_network_04880e_idx',
        ),
        migrations.RenameIndex(
            model_name='cellinfo',
            new_name='idx_device_cell',
            old_name='mqtt_cellin_device__0c50af_idx',
        ),
        migrations.AddIndex(
            model_name='cellinfo',
            index=models.Index(fields=['device', '-event_datetime'], name='idx_device_event_desc'),
        ),
    ]
