# Generated by Django 4.2.20 on 2026-04-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0008_remove_cellinfo_mqtt_cellin_network_e10b5b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellinfo',
            name='mcc_mnc',
        ),
        migrations.AddField(
            model_name='cellinfo',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to='mqtt.operator', verbose_name='Оператор'),
        ),
    ]
