# Generated by Django 4.2.20 on 2026-04-08 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0009_remove_cellinfo_mcc_mnc_cellinfo_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Cell ID')),
                ('rat', models.CharField(choices=[('2G', 'GSM (2G)'), ('3G', 'UMTS (3G)'), ('4G', 'LTE (4G)')], max_length=8, verbose_name='Тип сети')),
                ('freq', models.PositiveIntegerField(blank=True, help_text='Arfcn or Uarfcn or Earfcn - Абсолютный номер частотного канала в зависимости от типа сети', null=True, verbose_name='Номер частотного канала')),
                ('tac', models.PositiveIntegerField(blank=True, help_text='TAC (Tracking Area Code) - идентификаторы групп базовых станций в сотовой связи 4G', null=True, verbose_name='TAC (4G)')),
                ('lac', models.PositiveIntegerField(blank=True, help_text='LAC (Location Area Code) - идентификаторы групп базовых станций в сотовой связи 2G и 3G', null=True, verbose_name='LAC (2G/3G)')),
                ('pci', models.PositiveSmallIntegerField(blank=True, help_text='PCI (Physical Cell ID) — идентификатор базовой станции в сетях 4G', null=True, verbose_name='PCI')),
                ('psc', models.PositiveSmallIntegerField(blank=True, help_text='PSC (Primary Scrambling Code) - идентификатор базовой станции в сетях 3G', null=True, verbose_name='PSC')),
                ('bsic', models.PositiveSmallIntegerField(blank=True, help_text='BSIC (Base station ID code) - идентификатор базовой станции в сетях 2G', null=True, verbose_name='BSIC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cells', to='mqtt.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'сота',
                'verbose_name_plural': 'Соты',
                'ordering': ['-cell_id', 'operator'],
            },
        ),
        migrations.CreateModel(
            name='CellMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Индекс соты в списке')),
                ('cba', models.BooleanField(blank=True, help_text='Cell Bar indicator (TRUE=доступ запрещен, FALSE=доступ разрешен)', null=True, verbose_name='Запрет доступа к соте')),
                ('event_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время регистрации')),
                ('rsrp', models.SmallIntegerField(blank=True, help_text=('RSRP (Reference Signal Received Power) - уровень сигнала 4G',), null=True, verbose_name='RSRP (dBm)')),
                ('rsrq', models.SmallIntegerField(blank=True, help_text=('RSRQ (Reference Signal Received Quality) - качество сигнала 4G',), null=True, verbose_name='RSRQ (dB)')),
                ('rscp', models.SmallIntegerField(blank=True, help_text='RSCP (Received signal Code power) - уровень сигнала 3G', null=True, verbose_name='RSCP (dBm)')),
                ('ecno', models.SmallIntegerField(blank=True, help_text='Ec/No (Ratio of energy per modulating bit to the noise spectral density) - качество сигнала 3G', null=True, verbose_name='Ec/No (dB)')),
                ('rssi', models.SmallIntegerField(blank=True, help_text='RSSI (Received Signal Strength Indicator) - уровень сигнала 2G', null=True, verbose_name='RSSI (dBm)')),
                ('rxlev', models.SmallIntegerField(blank=True, help_text='RXLEV (Received Signal Level) - показатель мощности радиосигнала в сетях 2G', null=True, verbose_name='RXLEV')),
                ('c1', models.SmallIntegerField(blank=True, help_text='C1 (Cell selection criterion) - критерий «пригодности» сигнала для работы в сетях 2G', null=True, verbose_name='C1')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='mqtt.cell', verbose_name='Сота')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='mqtt.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'показание соты',
                'verbose_name_plural': 'Показания сот',
                'ordering': ['-event_datetime', 'cell', 'device', '-rsrp', '-rscp', '-rssi', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='deviceoperator',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceoperator',
            name='operator',
        ),
        migrations.DeleteModel(
            name='CellInfo',
        ),
        migrations.DeleteModel(
            name='DeviceOperator',
        ),
        migrations.AddIndex(
            model_name='cellmeasure',
            index=models.Index(fields=['device', '-event_datetime'], name='idx_device_event_desc'),
        ),
        migrations.AddIndex(
            model_name='cellmeasure',
            index=models.Index(fields=['cell', '-event_datetime'], name='idx_cell_event_desc'),
        ),
        migrations.AddIndex(
            model_name='cellmeasure',
            index=models.Index(fields=['device', 'cell'], name='idx_device_cell'),
        ),
        migrations.AddConstraint(
            model_name='cellmeasure',
            constraint=models.UniqueConstraint(fields=('device', 'cell', 'event_datetime'), name='unique_device_cell'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['cell_id', 'operator'], name='idx_operator_cell_id'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('operator', 'cell_id'), name='unique_cell'),
        ),
    ]
