# Generated by Django 4.2.20 on 2026-04-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0010_cell_cellmeasure_remove_deviceoperator_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='mqtt.operator', verbose_name='Оператор'),
            preserve_default=False,
        ),
    ]
