# Generated by Django 4.2.20 on 2026-04-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0011_alter_cell_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmeasure',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='mqtt.device', verbose_name='Устройство'),
            preserve_default=False,
        ),
    ]
