# Generated by Django 4.2.20 on 2026-04-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0011_rename_macro_region_region_macroregion'),
        ('mqtt', '0012_alter_cellmeasure_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='ts.pole', verbose_name='Опора'),
        ),
    ]
