# Generated by Django 4.2.20 on 2026-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0013_device_pole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['-created_at', '-cell_id', 'operator'], 'verbose_name': 'сота', 'verbose_name_plural': 'Соты'},
        ),
        migrations.RemoveConstraint(
            model_name='cell',
            name='unique_cell',
        ),
        migrations.RemoveIndex(
            model_name='cell',
            name='idx_operator_cell_id',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='tac',
        ),
        migrations.AlterField(
            model_name='cell',
            name='lac',
            field=models.PositiveIntegerField(default=1, help_text='- LAC (Location Area Code) /  TAC (Tracking Area Code) - идентификаторы групп базовых станций', verbose_name='LAC (2G/3G) / TAC (4G)'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['operator', 'rat', 'lac', 'cell_id'], name='idx_cell_full_lookup'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('operator', 'rat', 'lac', 'cell_id'), name='unique_cell_per_operator_rat_lac'),
        ),
    ]
