# Generated by Django 4.2.20 on 2026-04-15 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0014_alter_cell_options_remove_cell_unique_cell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время последнего события'),
        ),
    ]
