# Generated by Django 4.2.20 on 2026-04-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0015_cell_last_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['-last_seen', '-cell_id', 'operator'], 'verbose_name': 'сота', 'verbose_name_plural': 'Соты'},
        ),
    ]
