# Generated by Django 4.2.20 on 2026-04-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0016_alter_cell_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmeasure',
            name='mongo_id',
            field=models.CharField(blank=True, db_index=True, help_text='Идентификатор документа из коллекции MongoDB', max_length=24, null=True, verbose_name='ID из MongoDB'),
        ),
    ]
