# Generated by Django 4.2.20 on 2026-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0017_cellmeasure_mongo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='lac',
            field=models.PositiveIntegerField(db_index=True, help_text='- LAC (Location Area Code) /  TAC (Tracking Area Code) - идентификаторы групп базовых станций', verbose_name='LAC (2G/3G) / TAC (4G)'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='rat',
            field=models.CharField(choices=[('2G', 'GSM (2G)'), ('3G', 'UMTS (3G)'), ('4G', 'LTE (4G)')], db_index=True, max_length=8, verbose_name='Тип сети'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gps_lat',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gps_lon',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Долгота'),
        ),
    ]
