MODEM_MAC_MAX_LEN = 17

MAX_EXUIPMENT_PER_PAGE = 30

MAX_CHECK_ASSETS_TTL = 300
CACHE_KEY_CHECK_ASSETS_RUN = 'assets:last_check_assets_run_time'

CACHE_ASSETS_STATUS_TTL = 1800
CACHE_KEY_ASSETS_STATUS_PREFIX = 'assets:status:'

CACHE_ASSETS_CANDIDATE_TTL = 1800
CACHE_KEY_ASSETS_CANDIDATE_PREFIX = 'assets:candidate:'
