# Generated by Django 4.2.20 on 2025-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_pswd', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'Тест',
                'db_table': 'monitoring_data',
                'managed': False,
            },
        ),
    ]
