# Generated by Django 4.2.20 on 2025-09-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdata',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'Тест'},
        ),
    ]
