from datetime import timedelta

MAX_PLR_REASON_LEN = 32

MAX_PLR_PER_PAGE = 15
MAX_PLR_CHANGE_LOG_PER_PAGE = 25

MAX_PLR_EMAILS_LINKS = 25

PLR_CHANGE_LOG_PER_PAGE = 100


CLEANUP_OLD_PLR_CHANGE_LOG_TTL = timedelta(days=90)

PLR_CHANGE_LOG_BATCH_SIZE = 1000
