# Generated by Django 4.2.20 on 2025-12-16 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='message_number', max_length=255, verbose_name='Номер обращения')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppealAttr',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, db_column='constant_text', null=True, verbose_name='Значение')),
                ('created_at', models.DateTimeField(db_column='time_stamp', default=django.utils.timezone.now, verbose_name='Добавлено в')),
            ],
            options={
                'verbose_name': 'атрибут обращения',
                'verbose_name_plural': 'Атрибуты обращений',
                'db_table': 'messages_constants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppealStatus',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='time_stamp', default=django.utils.timezone.now, verbose_name='Добавлено в')),
                ('date', models.DateField(blank=True, db_column='status_time', null=True, verbose_name='Дата статуса')),
                ('name', models.CharField(db_column='message_status', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'статус обращения',
                'verbose_name_plural': 'Статусы обращений',
                'db_table': 'messages_states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttrType',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('attribute_id', models.IntegerField(db_column='constant_number', unique=True, verbose_name='ID атрибута')),
                ('name', models.CharField(db_column='name', max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип атрибута',
                'verbose_name_plural': 'Типы атрибутов',
                'db_table': 'constant_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='claim_number', max_length=255, verbose_name='Номер заявки')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'claims',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimAttr',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, db_column='constant_text', null=True, verbose_name='Значение')),
                ('created_at', models.DateTimeField(db_column='time_stamp', default=django.utils.timezone.now, verbose_name='Добавлено в')),
            ],
            options={
                'verbose_name': 'атрибут заявки',
                'verbose_name_plural': 'Атрибуты заявок',
                'db_table': 'constants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='time_stamp', default=django.utils.timezone.now, verbose_name='Добавлено в')),
                ('date', models.DateField(blank=True, db_column='status_time', null=True, verbose_name='Дата статуса')),
                ('name', models.CharField(db_column='claim_status', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'db_table': 'claims_states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Declarant',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'юридическое лицо',
                'verbose_name_plural': 'Юр. лица',
                'db_table': 'declarant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, verbose_name='Сайт')),
                ('link', models.CharField(db_column='link', max_length=255, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'сайт сетевой компании',
                'verbose_name_plural': 'Сайты сетевых компаний',
                'db_table': 'personal_areas',
                'managed': False,
            },
        ),
    ]
