# Generated by Django 4.2.20 on 2025-12-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, verbose_name='Сайт')),
                ('link', models.CharField(db_column='link', max_length=255, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'сетевая компания',
                'verbose_name_plural': 'Сетевые компании',
                'db_table': 'personal_areas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
