# Generated by Django 4.2.20 on 2025-08-21 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ts', '0005_alter_basestationoperator_operator_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время добавления')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('incident_date', models.DateTimeField(db_index=True, verbose_name='Дата и время регистрации инцидента')),
                ('track_sla', models.BooleanField(db_index=True, default=True, verbose_name='Отслеживать SLA')),
                ('is_email_incident', models.BooleanField(db_index=True, verbose_name='Инцидент был зарегестрирован из почты')),
                ('base_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='ts.basestation', verbose_name='Базовая станция')),
            ],
            options={
                'verbose_name': 'инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'статус инцидента',
                'verbose_name_plural': 'Статусы инцидентов',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('sla_deadline', models.IntegerField(blank=True, null=True, verbose_name='Срок устранения аварии (мин)')),
                ('is_avr_incident', models.BooleanField(verbose_name='Можно ли этот инцидент назначить подрядчику')),
            ],
            options={
                'verbose_name': 'тип инцидента',
                'verbose_name_plural': 'Типы инцидентов',
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время добавления')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.incident')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.incidentstatus')),
            ],
            options={
                'verbose_name': 'история статусов инцидента',
                'verbose_name_plural': 'История статусов инцидентов',
                'unique_together': {('incident', 'status', 'insert_date')},
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.incidenttype', verbose_name='Тип инцидента'),
        ),
        migrations.AddField(
            model_name='incident',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='ts.pole', verbose_name='Связанная опора'),
        ),
        migrations.AddField(
            model_name='incident',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный пользователь'),
        ),
        migrations.AddField(
            model_name='incident',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='incidents', through='incidents.IncidentStatusHistory', to='incidents.incidentstatus', verbose_name='Статус инцидента'),
        ),
    ]
