# Generated by Django 4.2.20 on 2025-08-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='is_email_incident',
        ),
    ]
