# Generated by Django 4.2.20 on 2025-08-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_incident_is_email_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttype',
            name='is_avr_incident',
        ),
    ]
