# Generated by Django 4.2.20 on 2025-08-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_incidenttype_is_avr_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='track_sla',
        ),
        migrations.AddField(
            model_name='incident',
            name='is_incident_finish',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Обработка заявки завершена'),
        ),
        migrations.AddField(
            model_name='incident',
            name='was_new_msg',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Пришло новое сообщение по инциденту'),
            preserve_default=False,
        ),
    ]
