# Generated by Django 4.2.20 on 2025-08-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_remove_incident_track_sla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='was_new_msg',
        ),
    ]
