# Generated by Django 4.2.20 on 2025-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_remove_incident_was_new_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentstatushistory',
            name='comments',
            field=models.CharField(max_length=512, null=True, verbose_name='Комментарий'),
        ),
    ]
