# Generated by Django 4.2.20 on 2025-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incidentstatushistory_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='comments',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Комментарий'),
        ),
    ]
