# Generated by Django 4.2.20 on 2025-09-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_alter_incidentstatushistory_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_finish_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время завершения инцидента'),
        ),
    ]
