# Generated by Django 4.2.20 on 2025-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_incident_incident_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_auto_incident',
            field=models.BooleanField(default=True, verbose_name='Сформирован автоматически'),
        ),
    ]
