# Generated by Django 4.2.20 on 2025-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_incident_is_auto_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='code',
            field=models.CharField(blank=True, help_text='Используется в заголовках писем по заявке', max_length=32, null=True, verbose_name='Код'),
        ),
    ]
