# Generated by Django 4.2.20 on 2025-09-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_incident_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='code',
            field=models.CharField(blank=True, help_text='Используется в заголовках писем', max_length=32, null=True, verbose_name='Код'),
        ),
    ]
