# Generated by Django 4.2.20 on 2025-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_alter_incident_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='code',
            field=models.CharField(blank=True, help_text='Используется в заголовках писем', max_length=32, null=True, unique=True, verbose_name='Код'),
        ),
    ]
