# Generated by Django 4.2.20 on 2025-10-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_alter_incident_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория инцидента',
                'verbose_name_plural': 'Категории инцидентов',
            },
        ),
        migrations.CreateModel(
            name='IncidentCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_category_links', to='incidents.incidentcategory', verbose_name='Категория')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_category_links', to='incidents.incident', verbose_name='Инцидент')),
            ],
            options={
                'verbose_name': 'связь инцидента и категории',
                'verbose_name_plural': 'Связи инцидентов и категорий',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='incidents', through='incidents.IncidentCategoryRelation', to='incidents.incidentcategory', verbose_name='Категории инцидента'),
        ),
        migrations.AddConstraint(
            model_name='incidentcategoryrelation',
            constraint=models.UniqueConstraint(fields=('incident', 'category'), name='unique_incident_category'),
        ),
    ]
