# Generated by Django 4.2.20 on 2025-10-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_incidentcategory_incidentcategoryrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='avr_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время передачи на АВР'),
        ),
        migrations.AddField(
            model_name='incident',
            name='rvr_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время передачи на РВР'),
        ),
    ]
