# Generated by Django 4.2.20 on 2025-10-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_incident_avr_date_incident_rvr_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='avr_date',
            new_name='avr_start_date',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='rvr_date',
            new_name='rvr_start_date',
        ),
        migrations.AddField(
            model_name='incident',
            name='avr_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время закрытия АВР'),
        ),
        migrations.AddField(
            model_name='incident',
            name='rvr_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время закрытия РВР'),
        ),
    ]
