# Generated by Django 4.2.20 on 2025-10-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_rename_avr_date_incident_avr_start_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('avr_end_date__gte', models.F('avr_start_date')), ('avr_end_date__isnull', True), ('avr_start_date__isnull', True), _connector='OR'), name='avr_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('rvr_end_date__gte', models.F('rvr_start_date')), ('rvr_end_date__isnull', True), ('rvr_start_date__isnull', True), _connector='OR'), name='rvr_end_after_start'),
        ),
    ]
