# Generated by Django 4.2.20 on 2025-10-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_incident_avr_end_after_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentstatushistory',
            name='avr_category',
            field=models.BooleanField(blank=True, null=True, verbose_name='Категория АВР'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='categories_at_status_change',
            field=models.ManyToManyField(blank=True, related_name='status_histories_with_categories', to='incidents.incidentcategory', verbose_name='Категории на момент смены статуса'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='dgu_category',
            field=models.BooleanField(blank=True, null=True, verbose_name='Категория ДГУ'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='rvr_category',
            field=models.BooleanField(blank=True, null=True, verbose_name='Категория РВР'),
        ),
    ]
