# Generated by Django 4.2.20 on 2025-10-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_incidentstatushistory_avr_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentstatushistory',
            old_name='avr_category',
            new_name='is_avr_category',
        ),
        migrations.RenameField(
            model_name='incidentstatushistory',
            old_name='dgu_category',
            new_name='is_dgu_category',
        ),
        migrations.RenameField(
            model_name='incidentstatushistory',
            old_name='rvr_category',
            new_name='is_rvr_category',
        ),
    ]
