# Generated by Django 4.2.20 on 2025-10-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0018_rename_avr_category_incidentstatushistory_is_avr_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentstatushistory',
            name='categories_at_status_change',
        ),
    ]
