# Generated by Django 4.2.20 on 2025-10-27 17:17

import datetime
from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0019_remove_incidentstatushistory_categories_at_status_change'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('avr_start_date__gte', django.db.models.functions.comparison.Least(models.F('insert_date'), models.F('incident_date'))), ('avr_start_date__isnull', True), _connector='OR'), name='avr_start_after_min_date'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('rvr_start_date__gte', django.db.models.functions.comparison.Least(models.F('insert_date'), models.F('incident_date'))), ('rvr_start_date__isnull', True), _connector='OR'), name='rvr_start_after_min_date'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('avr_end_date__lte', datetime.datetime(2025, 10, 27, 17, 22, 13, 168990, tzinfo=datetime.timezone.utc)), ('avr_end_date__isnull', True), _connector='OR'), name='avr_end_not_in_future'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('rvr_end_date__lte', datetime.datetime(2025, 10, 27, 17, 22, 13, 169051, tzinfo=datetime.timezone.utc)), ('rvr_end_date__isnull', True), _connector='OR'), name='rvr_end_not_in_future'),
        ),
    ]
