# Generated by Django 4.2.20 on 2025-10-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0020_incident_avr_start_after_min_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incident',
            name='avr_end_not_in_future',
        ),
        migrations.RemoveConstraint(
            model_name='incident',
            name='rvr_end_not_in_future',
        ),
    ]
