# Generated by Django 4.2.20 on 2025-10-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_remove_incident_avr_end_not_in_future_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='is_avr_category',
            field=models.BooleanField(default=True, verbose_name='Категория АВР'),
        ),
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='is_dgu_category',
            field=models.BooleanField(default=False, verbose_name='Категория ДГУ'),
        ),
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='is_rvr_category',
            field=models.BooleanField(default=False, verbose_name='Категория РВР'),
        ),
    ]
