# Generated by Django 4.2.20 on 2025-11-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0022_alter_incidentstatushistory_is_avr_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('css_class', models.CharField(blank=True, help_text='Используется для визуального отображения статуса в интерфейсе.', max_length=256, null=True, verbose_name='CSS-класс')),
            ],
            options={
                'verbose_name': 'категория статуса инцидента',
                'verbose_name_plural': 'Категории статусов инцидентов',
            },
        ),
        migrations.AddField(
            model_name='incidentstatus',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='incidents.incidentstatuscategory', verbose_name='Категория'),
        ),
    ]
