# Generated by Django 4.2.20 on 2025-11-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0023_incidentstatuscategory_incidentstatus_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentStatusCategory',
            new_name='StatusType',
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'verbose_name': 'тип статуса', 'verbose_name_plural': 'Типы статусов'},
        ),
    ]
