# Generated by Django 4.2.20 on 2025-11-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0024_rename_incidentstatuscategory_statustype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentstatus',
            name='category',
        ),
        migrations.AddField(
            model_name='incidentstatus',
            name='status_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_types', to='incidents.statustype', verbose_name='Тип статуса'),
        ),
    ]
