# Generated by Django 4.2.20 on 2025-11-12 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0025_remove_incidentstatus_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='Описание действия, совершённого с инцидентом', verbose_name='Действие')),
                ('insert_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время добавления')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='incidents.incident', verbose_name='Инцидент')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История инцидента',
                'verbose_name_plural': 'История инцидентов',
                'ordering': ['-insert_date'],
            },
        ),
    ]
