# Generated by Django 4.2.20 on 2025-11-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0026_incidenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenthistory',
            name='action',
            field=models.CharField(help_text='Описание действия, совершённого с инцидентом', max_length=1024, verbose_name='Действие'),
        ),
    ]
