# Generated by Django 4.2.20 on 2025-11-13 17:48

from django.db import migrations, models
import django.db.models.deletion
import incidents.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0027_alter_incidenthistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatus',
            name='status_type',
            field=models.ForeignKey(default=incidents.models.get_default_status_type, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_types', to='incidents.statustype', verbose_name='Тип статуса'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='css_class',
            field=models.CharField(default='default', help_text='Используется для визуального отображения статуса в интерфейсе.', max_length=256, verbose_name='CSS-класс'),
        ),
    ]
