# Generated by Django 4.2.20 on 2025-12-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0028_alter_incidentstatus_status_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'подкатегория инцидента',
                'verbose_name_plural': 'Подкатегории инцидентов',
            },
        ),
        migrations.CreateModel(
            name='CategorySubCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategory_links', to='incidents.incidentcategory', verbose_name='Категория')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategory_links', to='incidents.incidentsubcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'связь категории и подкатегории',
                'verbose_name_plural': 'Связи категорий и подкатегорий',
            },
        ),
        migrations.AddConstraint(
            model_name='categorysubcategoryrelation',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_subcategory_per_category'),
        ),
    ]
