# Generated by Django 4.2.20 on 2025-12-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0029_incidentsubcategory_categorysubcategoryrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'подтип инцидента',
                'verbose_name_plural': 'Подтипы инцидентов',
            },
        ),
        migrations.CreateModel(
            name='TypeSubTypeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_subtype_links', to='incidents.incidentsubtype', verbose_name='Подтип инцидента')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_subtype_links', to='incidents.incidenttype', verbose_name=' Тип инцидента')),
            ],
            options={
                'verbose_name': 'связь типа и подтипа инцидента',
                'verbose_name_plural': 'Связи типов и подтипов инцидентов',
            },
        ),
        migrations.DeleteModel(
            name='CategorySubCategoryRelation',
        ),
        migrations.DeleteModel(
            name='IncidentSubCategory',
        ),
        migrations.AddConstraint(
            model_name='typesubtyperelation',
            constraint=models.UniqueConstraint(fields=('incident_type',), name='unique_subtype_per_type'),
        ),
    ]
