# Generated by Django 4.2.20 on 2025-12-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0030_incidentsubtype_typesubtyperelation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='typesubtyperelation',
            name='unique_subtype_per_type',
        ),
        migrations.AddConstraint(
            model_name='typesubtyperelation',
            constraint=models.UniqueConstraint(fields=('incident_type', 'incident_subtype'), name='unique_subtype_per_type'),
        ),
    ]
