# Generated by Django 4.2.20 on 2025-12-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0031_remove_typesubtyperelation_unique_subtype_per_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.incidentsubtype', verbose_name='Подтип инцидента'),
        ),
    ]
