# Generated by Django 4.2.20 on 2026-01-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0032_incident_incident_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='disable_thread_auto_link',
            field=models.BooleanField(db_index=True, default=False, help_text='Если True, инцидент исключается из авто-матчинга по thread', verbose_name='Запрет авто-привязки по email цепочке'),
        ),
    ]
