# Generated by Django 4.2.20 on 2026-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0033_incident_disable_thread_auto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='dgu_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время закрытия ДГУ'),
        ),
        migrations.AddField(
            model_name='incident',
            name='dgu_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время передачи на ДГУ'),
        ),
    ]
