# Generated by Django 4.2.20 on 2026-02-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0034_incident_dgu_end_date_incident_dgu_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_yt_tracker_controlled',
            field=models.BooleanField(default=True, help_text='Если True, управление этим инцидентом происходит из интерфейса YandexTracker', verbose_name='Использовать web форму YandexTracker'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='disable_thread_auto_link',
            field=models.BooleanField(default=False, help_text='Если True, инцидент исключается из авто-матчинга по thread', verbose_name='Запрет авто-привязки по email цепочке'),
        ),
    ]
