# Generated by Django 4.2.20 on 2026-02-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0035_incident_is_yt_tracker_controlled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentcategoryrelation',
            options={'ordering': ['category'], 'verbose_name': 'связь инцидента и категории', 'verbose_name_plural': 'Связи инцидентов и категорий'},
        ),
    ]
