# Generated by Django 4.2.20 on 2026-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0036_alter_incidentcategoryrelation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='was_read',
            field=models.BooleanField(default=True, verbose_name='Был ли просмотрен диспетчером'),
        ),
    ]
