# Generated by Django 4.2.20 on 2026-03-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0038_comment_comment_content_not_empty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='content_not_empty',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('content__regex', '^\\s|\\s$'), _negated=True), models.Q(('content', ''), _negated=True)), name='content_not_empty_or_whitespace_edges'),
        ),
    ]
