# Generated by Django 4.2.20 on 2026-04-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0039_remove_comment_content_not_empty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
