# Generated by Django 4.2.20 on 2026-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0040_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='is_yt_tracker_controlled',
            field=models.BooleanField(default=False, help_text='Если True, управление этим инцидентом происходит из интерфейса YandexTracker', verbose_name='Использовать web форму YandexTracker'),
        ),
    ]
