# Generated by Django 4.2.20 on 2026-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0041_alter_incident_is_yt_tracker_controlled'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='auto_close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время автоматического закрытия'),
        ),
    ]
