# Generated by Django 4.2.20 on 2026-04-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0042_incident_auto_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='auto_close_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время автоматического закрытия'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='was_read',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Был ли просмотрен диспетчером'),
        ),
    ]
