# Generated by Django 4.2.20 on 2026-05-14 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0043_alter_incident_auto_close_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Название поля модели', max_length=256, verbose_name='Поле')),
                ('old_value', models.CharField(blank=True, help_text='JSON строка или текст старого значения', max_length=1024, null=True, verbose_name='Старое значение')),
                ('new_value', models.CharField(blank=True, help_text='JSON строка или текст нового значения', max_length=1024, null=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил пользователь')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='incidents.incident', verbose_name='Инцидент')),
            ],
            options={
                'verbose_name': 'Журнал изменений инцидента',
                'verbose_name_plural': 'Журналы изменений инцидентов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', '-created_at'], name='incidents_i_inciden_ef53a5_idx')],
                'unique_together': {('incident', 'field_name', 'created_at')},
            },
        ),
    ]
