# Generated by Django 4.2.20 on 2026-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0044_incidentchangelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentchangelog',
            options={'ordering': ['-created_at', 'field_name', 'id'], 'verbose_name': 'журнал', 'verbose_name_plural': 'Журналы изменений'},
        ),
        migrations.AlterField(
            model_name='incident',
            name='was_read',
            field=models.BooleanField(db_index=True, default=True, help_text='Был ли просмотрен диспетчером', verbose_name='Прочитано'),
        ),
    ]
