# Generated by Django 4.2.20 on 2026-05-15 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0045_alter_incidentchangelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentchangelog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
    ]
