# Generated by Django 4.2.20 on 2026-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0046_alter_incidentchangelog_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentcategory',
            options={'ordering': ['name'], 'verbose_name': 'категория инцидента', 'verbose_name_plural': 'Категории инцидентов'},
        ),
        migrations.AlterModelOptions(
            name='incidentstatus',
            options={'ordering': ['name'], 'verbose_name': 'статус инцидента', 'verbose_name_plural': 'Статусы инцидентов'},
        ),
        migrations.AlterModelOptions(
            name='incidentsubtype',
            options={'ordering': ['name'], 'verbose_name': 'подтип инцидента', 'verbose_name_plural': 'Подтипы инцидентов'},
        ),
        migrations.AlterModelOptions(
            name='incidenttype',
            options={'ordering': ['name'], 'verbose_name': 'тип инцидента', 'verbose_name_plural': 'Типы инцидентов'},
        ),
        migrations.AddField(
            model_name='incident',
            name='related_incidents',
            field=models.ManyToManyField(blank=True, help_text='Инциденты, входящие в одну группу с данным', to='incidents.incident', verbose_name='Связанные инциденты'),
        ),
    ]
