# Generated by Django 4.2.20 on 2026-05-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0047_alter_incidentcategory_options_and_more'),
    ]

    operations = [
        # 1. Создаем новую таблицу связей IncidentLink
        migrations.CreateModel(
            name='IncidentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('related', 'Связана с'), ('subtask', 'Подзадача'), ('parent', 'Родительская'), ('depends_on', 'Зависит от'), ('blocks', 'Блокирует'), ('duplicate', 'Дублирует')], max_length=256, verbose_name='Тип связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания связи')),
                ('source_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='incidents.incident', verbose_name='Инициатор связи')),
                ('target_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='incidents.incident', verbose_name='Целевой инцидент')),
            ],
            options={
                'verbose_name': 'связь инцидентов',
                'verbose_name_plural': 'Связи инцидентов',
            },
        ),

        # 2. Добавляем ограничения для новой таблицы
        migrations.AddConstraint(
            model_name='incidentlink',
            constraint=models.CheckConstraint(check=~models.Q(source_incident_id=models.F('target_incident_id')), name='no_self_link'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentlink',
            unique_together={('source_incident', 'target_incident')},
        ),

        # 3. УДАЛЯЕМ старое поле related_incidents (все данные будут потеряны, но нам это не важно)
        migrations.RemoveField(
            model_name='incident',
            name='related_incidents',
        ),

        # 4. СОЗДАЕМ новое поле related_incidents с правильным through
        migrations.AddField(
            model_name='incident',
            name='related_incidents',
            field=models.ManyToManyField(
                blank=True, 
                help_text='Инциденты, входящие в группу (управляется через типы связей)', 
                related_name='linked_to_me', 
                through='incidents.IncidentLink', 
                to='incidents.incident', 
                verbose_name='Связанные инциденты'
            ),
        ),
    ]