# Generated by Django 4.2.20 on 2026-05-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0048_incidentlink_alter_incident_related_incidents_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentlink',
            options={'verbose_name': 'cвязь инцидентов', 'verbose_name_plural': 'Связи инцидентов'},
        ),
        migrations.AlterField(
            model_name='incident',
            name='related_incidents',
            field=models.ManyToManyField(blank=True, help_text='Инциденты, входящие в группу (управляется через типы связей)', through='incidents.IncidentLink', to='incidents.incident', verbose_name='Связанные инциденты'),
        ),
    ]
