# Generated by Django 4.2.20 on 2026-05-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0049_alter_incidentlink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentlink',
            name='link_type',
            field=models.CharField(choices=[('related', 'Связана с'), ('duplicate', 'Дублирует'), ('parent', 'Родительская'), ('subtask', 'Подзадача'), ('blocks', 'Блокирует'), ('depends_on', 'Зависит от')], max_length=256, verbose_name='Тип связи'),
        ),
        migrations.AddIndex(
            model_name='incidentlink',
            index=models.Index(fields=['source_incident', 'target_incident'], name='incidents_i_source__0460ce_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentlink',
            index=models.Index(fields=['target_incident', 'source_incident'], name='incidents_i_target__4e92e1_idx'),
        ),
    ]
