# Generated by Django 4.2.20 on 2026-05-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0051_incidentlink_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentlink',
            name='created_by',
        ),
    ]
