# Generated by Django 4.2.20 on 2026-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0052_remove_incidentlink_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentstatushistory',
            name='is_eks_category',
            field=models.BooleanField(default=False, verbose_name='Категория ЭКС'),
        ),
    ]
