# Generated by Django 4.2.20 on 2026-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0053_incidentstatushistory_is_eks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='eks_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время закрытия ЭКС'),
        ),
        migrations.AddField(
            model_name='incident',
            name='eks_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время передачи на ЭКС'),
        ),
    ]
