# Generated by Django 4.2.20 on 2026-06-08 14:49

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0054_incident_eks_end_date_incident_eks_start_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('dgu_end_date__gte', models.F('dgu_start_date')), ('dgu_end_date__isnull', True), ('dgu_start_date__isnull', True), _connector='OR'), name='dgu_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('eks_end_date__gte', models.F('eks_start_date')), ('eks_end_date__isnull', True), ('eks_start_date__isnull', True), _connector='OR'), name='eks_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('dgu_start_date__gte', django.db.models.functions.comparison.Least(models.F('insert_date'), models.F('incident_date'))), ('dgu_start_date__isnull', True), _connector='OR'), name='dgu_start_after_min_date'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('eks_start_date__gte', django.db.models.functions.comparison.Least(models.F('insert_date'), models.F('incident_date'))), ('eks_start_date__isnull', True), _connector='OR'), name='eks_start_after_min_date'),
        ),
    ]
