# Generated by Django 4.2.20 on 2026-06-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0055_incident_dgu_end_after_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(db_index=True, max_length=2048, verbose_name='Сообщение'),
        ),
    ]
