# Generated by Django 4.2.20 on 2026-08-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0056_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVRPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('sla_deadline', models.IntegerField(blank=True, null=True, verbose_name='Срок устранения аварии (мин)')),
            ],
            options={
                'verbose_name': 'ПР',
                'verbose_name_plural': 'Приоритет РВР',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='rvr_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.rvrpriority', verbose_name='Приоритет РВР'),
        ),
    ]
