# Generated by Django 4.2.20 on 2026-08-21 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0057_rvrpriority_incident_rvr_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('important', 'Важный'), ('critical', 'Критичный')], db_index=True, default='normal', max_length=16, verbose_name='Важность')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='incidents.incident', verbose_name='Инцидент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный инцидент',
                'verbose_name_plural': 'Избранные инциденты',
            },
        ),
        migrations.AddConstraint(
            model_name='incidentfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'incident'), name='uniq_user_incident_favorite'),
        ),
    ]
