# Generated by Django 4.2.20 on 2026-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0058_incidentfavorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentfavorite',
            name='priority',
            field=models.CharField(choices=[('normal', 'Обычный'), ('important', 'Важный')], db_index=True, default='normal', max_length=16, verbose_name='Важность'),
        ),
    ]
