# Generated by Django 4.2.20 on 2026-08-25 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0060_incident_region_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentstatushistory',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
