# Generated by Django 4.2.20 on 2026-09-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0061_incidentstatushistory_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Источник регистрации',
                'verbose_name_plural': 'Источники регистрации',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.incidentsourcetype', verbose_name='Источник регистрации'),
        ),
    ]
