# Generated by Django 4.2.20 on 2026-10-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0016_alter_region_rvr_email'),
        ('incidents', '0062_incidentsourcetype_incident_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionRvrEmailAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.ManyToManyField(related_name='region_assignments', to='ts.contractoremail', verbose_name='Email подрядчика по РВР')),
                ('incident_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rvr_email_assignments', to='incidents.incidentsubtype', verbose_name='Подтип инцидента')),
                ('incident_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rvr_email_assignments', to='incidents.incidenttype', verbose_name='Тип инцидента')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvr_email_assignments', to='ts.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'назначение email РВР',
                'verbose_name_plural': 'Назначения email РВР',
            },
        ),
        migrations.AddConstraint(
            model_name='regionrvremailassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('incident_subtype__isnull', True), ('incident_type__isnull', True)), fields=('region',), name='uniq_rvr_assign_region_only'),
        ),
        migrations.AddConstraint(
            model_name='regionrvremailassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('incident_subtype__isnull', True)), fields=('region', 'incident_type'), name='uniq_rvr_assign_region_type'),
        ),
        migrations.AddConstraint(
            model_name='regionrvremailassignment',
            constraint=models.UniqueConstraint(fields=('region', 'incident_type', 'incident_subtype'), name='uniq_rvr_assign_full'),
        ),
    ]
