# Generated by Django 4.2.20 on 2026-10-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0017_volscontractor_vols'),
        ('incidents', '0063_regionrvremailassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='vols',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='ts.vols', verbose_name='ВОЛС'),
        ),
    ]
