# Generated by Django 4.2.20 on 2026-03-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_level_alter_notification_send_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled',
            field=models.BooleanField(default=False, verbose_name='Добавлено ли уведомление в Cellery'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('low', 'Приоритет: Низкий'), ('medium', 'Приоритет: Средний'), ('high', 'Приоритет: Высокий')], default='medium', max_length=16, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Тема'),
        ),
    ]
