# Generated by Django 4.2.20 on 2026-03-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_scheduled_alter_notification_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='scheduled',
            field=models.BooleanField(default=False, verbose_name='Добавлено уведомление в Cellery'),
        ),
    ]
