# Generated by Django 4.2.20 on 2026-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
