import os

GRAFANA_URL = os.getenv('GRAFANA_URL', 'http://127.0.0.1:3000')

GENERAL_DISPATCH_STATISTICS_UID = os.getenv('GENERAL_DISPATCH_STATISTICS_UID')

GENERAL_DISPATCH_STATISTICS_SLUG = 'public-dashboards'
